#
# Copyright (C) 2026 Linux Studio Plugins Project <https://lsp-plug.in/>
#           (C) 2026 Vladimir Sadovnikov <sadko4u@gmail.com>
#
# This file is part of lsp-plugins-shared
#
# lsp-plugins-shared is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# lsp-plugins-shared is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with lsp-plugins-shared.  If not, see <https://www.gnu.org/licenses/>.
#

uninstall_old_xdg_icons:
	echo "Removing legacy desktop icons"
	-rm "$(XDG_DIR_PATH)/lsp-plugins.directory"
	-rm "$(XDG_MENU_PATH)/lsp-plugins.menu"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x2_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x2_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x4_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x4_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x8_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ab_tester_x8_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_art_delay_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_art_delay_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_autogain_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_autogain_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_autogain_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_autogain_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_beat_breather_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_beat_breather_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_chorus_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_chorus_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_clipper_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_clipper_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_comp_delay_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_comp_delay_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_comp_delay_x2_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_crossover_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_crossover_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_crossover_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_crossover_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_dyna_processor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_dyna_processor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_dyna_processor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_dyna_processor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_dyna_processor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_dyna_processor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_dyna_processor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_dyna_processor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_expander_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_expander_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_expander_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_expander_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_expander_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_expander_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_expander_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_expander_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_filter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_filter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_flanger_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_flanger_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gate_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gate_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gate_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gate_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gate_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gate_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gate_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gate_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gott_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gott_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gott_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_gott_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gott_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gott_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gott_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_gott_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x16_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x16_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x16_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x16_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x32_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x32_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x32_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_graph_equalizer_x32_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_impulse_responses_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_impulse_responses_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_impulse_reverb_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_impulse_reverb_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_latency_meter.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_limiter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_limiter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_limiter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_limiter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_loud_comp_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_loud_comp_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_matcher_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_matcher_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_matcher_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_matcher_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_clipper_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_clipper_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_compressor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_compressor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_compressor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_compressor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_dyna_processor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_dyna_processor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_dyna_processor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_dyna_processor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_dyna_processor_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_dyna_processor_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_dyna_processor_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_dyna_processor_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_expander_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_expander_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_expander_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_expander_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_expander_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_expander_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_expander_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_expander_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_gate_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_gate_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_gate_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_gate_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_gate_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_gate_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_gate_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_gate_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_limiter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_limiter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_limiter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sc_mb_limiter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_ringmod_sc_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mb_ringmod_sc_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x16_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x16_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x4_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x4_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x8_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_mixer_x8_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_noise_generator_x1.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_noise_generator_x2.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_noise_generator_x4.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_oscillator_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_oscilloscope_x1.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_oscilloscope_x2.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_oscilloscope_x4.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x16_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x16_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x16_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x16_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x32_lr.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x32_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x32_ms.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_para_equalizer_x32_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_phase_detector.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_phaser_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_phaser_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_profiler_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_profiler_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_referencer_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_referencer_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_return_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_return_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ringmod_sc_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_ringmod_sc_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_room_builder_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_room_builder_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x12.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x12_do.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x24.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x24_do.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x48.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_multisampler_x48_do.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sampler_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_sampler_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_send_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_send_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_slap_delay_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_slap_delay_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x1.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x12.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x16.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x2.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x4.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_spectrum_analyzer_x8.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_surge_filter_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_surge_filter_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_trigger_midi_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_trigger_midi_stereo.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_trigger_mono.desktop"
	-rm "$(XDG_APP_PATH)/in.lsp_plug.lsp_plugins_trigger_stereo.desktop"

